name: ncssm_lectures
channels:
  - defaults
  - conda-forge
dependencies:
  - dynaconf=3.2.6 # for configuration settings
  - gymnasium-all=1.0.0 # for the gym environments
  - matplotlib=3.9.2 # for plotting
  - numpy<2.0 # for numerical stuff. numpy 2+ causes issues with tensorboard!
  - opencv=4.10.0 # for generating videos
  - pandas=2.2.3 # for data manipulations
  - pillow=10.3.0 # for manipulating images
  - python=3.11 # for setting the python version
  - pytorch=2.3.1 # for neural network stuff
  - tensorboard=2.17.0 # for monitoring (neural network) training
  - tqdm=4.66.5 # for nice loop minitoring
